### ISSUE TITLE
GitHub Actions cron job not running

### ISSUE THREAD

**Issue by damdo** [gokrazy-community/firmware-rpi#1]
The GH action cronjob has not been running in a while.

Looking at the workflow UI [here](https://github.com/gokrazy-community/firmware-rpi/actions/workflows/cron.yml) it says:

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs.

Do we need to add some sort of automation to keep that up and running?

**Comment by damdo** [comment]
cc. @oliverpool

**Comment by oliverpool** [comment]
Thanks for the ping. I didn't know that github disabled cron jobs after a while (and I don't recall getting a notification about it).

I re-enabled it and triggered a manual workflow.

> Do we need to add some sort of automation to keep that up and running?

You mean something like https://github.com/marketplace/actions/keepalive-workflow ? We can give it a try.

**Comment by oliverpool** [comment]
I have added the keepalive action as well as automatic tagging, for nicer versions: 45c6628c0e19986bae2e7f3b9abe48d1f1789a4c

Should be close this issue for now and check in 55 days if it works?

**Comment by damdo** [comment]
Yeah that's, exactly what I had in mind.
Thank you very much! I tested the new released version and it worked for me. I think we can close this now, and if we get stuck again we can re-open.

**Comment by damdo** [comment]
Do we want to add this same keepalive also to the kernel repo?

**Comment by oliverpool** [comment]
Done in https://github.com/gokrazy-community/kernel-rpi-os-32/commit/143aee3c202e0762663d5df0973bd18f53b436d2

**Comment by damdo** [comment]
Thanks!
